version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        build: ./php/
        container_name: php
        volumes:
            - ./src:/var/www/html
        command: >
            sh -c "/root/dockerrun.sh &&
            php-fpm"
